= Introduction

This document defines specific DGIWG requirements, recommendations and guidelines for implementations of the ISO / OGC Web Map Service standard which is based on ISO 19128:2005 Web Map Server Interface / OpenGIS Web Map Server Implementation Specification 1.3.0.

A Web Map Service (WMS) produces maps of spatially referenced data dynamically from geographic information.

The OGC WMS Interface offers 3 Operations:

* GetCapabilities (mandatory): Allows for obtaining Service Metadata
* GetMap (mandatory): Returns a map
* GetFeatureInfo (optional): Provides additional information about features in the pictures of maps that were returned by previous GetMap requests

The WMS Implementation Specification defines two conformance classes, “Basic WMS” and “Queryable WMS”.

The Basic WMS supports the mandatory GetCapabilities and GetMap operations (requests and responses) whereas the Queryable WMS supports all Basic WMS operations and the GetFeatureInfo operation.

*Software implementations that claim to be conformant with the DGIWG WMS profile shall support the Queryable WMS, as well as the specifically defined requirements in this document.*

The DGIWG WMS profile is written in such a way that it references the different operations and parameters of the base standard and then defines specific requirements for software implementation.
